In [74]:
import numpy as np
from sklearn.linear_model import LogisticRegression
import pandas as pd
train_data = pd.read_csv("/Users/Dhairya/Downloads/Titanic-Dataset.csv")
train_data.drop(["Name","Ticket","PassengerId"],axis = 1 , inplace = True)
train_data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [75]:
train_data["Age"].fillna(train_data["Age"].mean(),inplace = True)
train_data.isnull().sum()


Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [76]:
train_data.loc[train_data["Sex"]=='female','Sex']= 0

In [77]:
train_data.loc[train_data["Sex"]=='male','Sex']= 1

In [78]:
train_data.head()

Survived  Pclass Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3   1  22.0      1      0   7.2500   NaN        S
1         1       1   0  38.0      1      0  71.2833   C85        C
2         1       3   0  26.0      0      0   7.9250   NaN        S
3         1       1   0  35.0      1      0  53.1000  C123        S
4         0       3   1  35.0      0      0   8.0500   NaN        S

In [79]:
train_data.loc[train_data["Embarked"].isnull(),"Embarked"]='S'

In [80]:
train_data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      0
dtype: int64

In [81]:
train_data.loc[train_data["Embarked"] == 'S',"Embarked"]= 1
train_data.loc[train_data["Embarked"] == 'C',"Embarked"]= 2
train_data.loc[train_data["Embarked"] == 'Q',"Embarked"]= 3

In [82]:
train_data.loc[train_data['Cabin'].isnull(),'Cabin']= 0
train_data.loc[train_data['Cabin'] !=0,'Cabin']= 1


In [84]:
print(train_data.head())
X = train_data.values
X.shape

   Survived  Pclass Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3   1  22.0      1      0   7.2500     0        1
1         1       1   0  38.0      1      0  71.2833     1        2
2         1       3   0  26.0      0      0   7.9250     0        1
3         1       1   0  35.0      1      0  53.1000     1        1
4         0       3   1  35.0      0      0   8.0500     0        1


(891, 9)

In [87]:
X[:,0]

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [88]:
Y = X[:,0].astype('int')
X = X[:,1:9]

print(X)
print(Y)

[[3 1 22.0 ... 7.25 0 1]
 [1 0 38.0 ... 71.2833 1 2]
 [3 0 26.0 ... 7.925 0 1]
 ...
 [3 0 29.69911764705882 ... 23.45 0 1]
 [1 1 26.0 ... 30.0 1 2]
 [3 1 32.0 ... 7.75 0 3]]
[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 

In [89]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [90]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3)

In [91]:
scaler = preprocessing.StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
print(x_train)
print(x_train.shape,y_train.shape)

[[ 0.82623021  0.72850019 -0.64918278 ... -0.51935669 -0.54581743
  -0.5616825 ]
 [-1.59039617 -1.37268323  0.65726534 ...  0.87879613  1.83211445
   1.03616315]
 [-1.59039617  0.72850019  0.11931611 ...  0.45242268  1.83211445
  -0.5616825 ]
 ...
 [ 0.82623021 -1.37268323  1.19521456 ... -0.37775329 -0.54581743
   1.03616315]
 [-1.59039617 -1.37268323  0.04246622 ...  1.2152529   1.83211445
  -0.5616825 ]
 [ 0.82623021 -1.37268323  0.65726534 ... -0.00334074 -0.54581743
  -0.5616825 ]]
(623, 8) (623,)


In [92]:
clf=LogisticRegression(solver='saga', max_iter=1000, tol=0.00001)

In [93]:
clf.fit(x_train,y_train)

LogisticRegression(max_iter=1000, solver='saga', tol=1e-05)

In [94]:
clf.score(x_train,y_train)

0.7897271268057785

In [95]:
x_test.shape


(268, 8)

In [96]:
x_test = scaler.transform(x_test)

In [97]:
titanic_prediction= clf.predict(x_test)

In [98]:
print(titanic_prediction)

[0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 1 1 0 1 0
 1 0 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 1
 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 0 0 0 1 0
 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1 0 1 0 1
 0 0 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 1 1 1 0 0 0
 1 1 0 0 1 1 0 0 0]


In [99]:
from sklearn.metrics import classification_report

In [101]:
print(classification_report(y_test,titanic_prediction))

              precision    recall  f1-score   support

           0       0.83      0.92      0.88       153
           1       0.88      0.76      0.81       115

    accuracy                           0.85       268
   macro avg       0.86      0.84      0.84       268
weighted avg       0.85      0.85      0.85       268

